### ISSUE TITLE
Database Structure

### ISSUE THREAD

**Issue by rbrown511** [rbrown511/cohort-connected#1]
- [x] Determining the number and scope of collections
- [x] Mapping fields needed within each collection
- [x] Evaluating crossover fields that can be populated

**Comment by tacrawford91** [comment]
https://docs.google.com/document/d/1S0vYfKz1bJg__x2s4Jn7jvam5AjmBZCqwbZpJYQ1wK4/edit

data table/ collection table starts on page 2
