### ISSUE TITLE
LinkedIn Authorization

### ISSUE THREAD

**Issue by rbrown511** [rbrown511/cohort-connected#4]
## Find answers to the following questions:
- [x] What profile information can be accessed by linking our user authentication through LinkedIn?
- [x] If the user does not have a LinkedIn account, what is the default message returned? Can this be tweaked so that we can create our own message to the user?
- [x] What input fields must our front end include to support LinkedIn auth?

**Comment by tacrawford91** [comment]
Data to pull:
Name:
Image:
Current Position:
Company:

**Comment by Salty923** [comment]
Forked an example repo and was able to get it working with our credentials.  We can pull all of the profile information including the picture.
