### ISSUE TITLE
Component Mapping

### ISSUE THREAD

**Issue by tacrawford91** [rbrown511/cohort-connected#5]
## Analyzing wireframes to map out the React components needed
- [x] Login Page
- [x] Dashboard (Home) Page
- [x] Resources Page
- [x] Messages Page

_Bonus: Look into what it would take to have active messages pinned to the bottom of the browser screen while a user is logged in._

**Comment by rbrown511** [comment]
@tacrawford91 Started mapping components on the Moqup: https://app.moqups.com/rbrown511@gmail.com/TNDJ63uMch/edit/page/a8b765458

**Comment by tacrawford91** [comment]
Mapped out mainPage with wrappers and next level components. Color coded by level - Base Level: gray, 2: red, 3: Yellow. The page components will require more components but hard to predict at this time. let me know if the naming scheme used for my components is acceptable/clear.
