### ISSUE TITLE
Event Scrape 

### ISSUE THREAD

**Issue by tacrawford91** [rbrown511/cohort-connected#6]
- [ ] **Which website(s) will we be scraping tech-focused events from?**
_Previously suggested: Meetup, Built In Chicago_

### Make sure we can target the following data:
- Name of Event
- Date and Time
- Location
- Description
- Link

### It would also be nice to include:
- Number of Attendees
- Person or Group(s) Hosting the Event

_Please comment with websites that fulfill these needs_

**Comment by rbrown511** [comment]
https://www.reuters.com/news/technology

**Comment by tacrawford91** [comment]
Task Moved to actual project work.
