### ISSUE TITLE
News Scrape

### ISSUE THREAD

**Issue by tacrawford91** [rbrown511/cohort-connected#8]
- [ ] **Which website(s) will we be scraping tech news from?**

### Make sure we can target the following data:
- Article Title
- Brief Summary
- Link to Full Article (for further reading)
- Image

### It would also be nice to include:
- Author
- Date of Article's Publication

_Please comment with websites that fulfill these needs_

**Comment by rbrown511** [comment]
https://www.reuters.com/news/technology

**Comment by tacrawford91** [comment]
Task Moved to actual project work.
